### ISSUE TITLE
demo not working for queries 

### ISSUE THREAD

**Issue by pierrelambert** [redis-field-engineering/redis-smart-cache#29]
smart-cache-cli : 

<img width="840" alt="image" src="https://github.com/redis-field-engineering/redis-smart-cache/assets/7335930/6894a362-caaa-4a1e-b095-80b28ea53b32">

<img width="671" alt="image" src="https://github.com/redis-field-engineering/redis-smart-cache/assets/7335930/db9066d9-9689-474d-b4a1-5e7cc55d6481">

while the data is actually : 

<img width="524" alt="image" src="https://github.com/redis-field-engineering/redis-smart-cache/assets/7335930/2fcca36d-814f-4270-88b7-653d12ba827c">

**Comment by pierrelambert** [comment]
I have a suspect for this one , I see usage of  "smartcache:queries" 
 core/redis-smart-cache-jdbc/src/main/java/com/redis/smartcache/Driver.java 
=> 	public static final String KEYSPACE_QUERIES = "queries"; 
tools/redis-smart-cache-cli/src/main/java/com/redis/smartcache/cli/commands/Commands.java
=>   TableSelector<QueryInfo, SelectorItem<QueryInfo>> component = new TableSelector<>(getTerminal(),
                queries, "queries", null, QueryInfo.getHeaderRow((getTerminal().getWidth()-10)/8));
                
Or "smartcache:query":                
tools/redis-smart-cache-cli/src/main/java/com/redis/smartcache/cli/RedisServiceImpl.java
 => 
    static String HashKeyName(String applicationName, String id){
        return String.format("%s:query:%s", applicationName, id);

    }
    
I think there is a need for reconciliation.

**Comment by banker** [comment]
@pierrelambert This is being fixed in https://github.com/redis-field-engineering/redis-smart-cache/pull/30#pullrequestreview-1753516060

**Comment by slorello89** [comment]
@pierrelambert - I see it, we use timeseries to get all the metrics so the key is computed by the CLI, I've corrected the CLI to use the correct key-names.
